using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using MyStore.Api.Data;using MyStore.Api.Models;
namespace MyStore.Api.Controllers;
[ApiController][Route("api/products")]public class ProductsController:ControllerBase{readonly AppDbContext db;public ProductsController(AppDbContext db)=>this.db=db;
[HttpGet]public async Task<IActionResult> Get(string? search,string? category){var q=db.Products.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Title.Contains(search)||x.Description.Contains(search));if(!string.IsNullOrWhiteSpace(category)&&category!="all")q=q.Where(x=>x.Category==category);return Ok(await q.OrderByDescending(x=>x.IsFeatured).ThenBy(x=>x.Id).ToListAsync());}
[HttpGet("categories")]public async Task<IActionResult> Categories()=>Ok(await db.Products.Select(x=>x.Category).Distinct().OrderBy(x=>x).ToListAsync());
[HttpGet("{id:int}")]public async Task<IActionResult> One(int id){var p=await db.Products.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id);return p is null?NotFound(new{message="Product not found."}):Ok(p);}
[Authorize(Roles="Admin")][HttpPost]public async Task<IActionResult>Create(Product p){p.Id=0;db.Products.Add(p);await db.SaveChangesAsync();return Ok(p);}
[Authorize(Roles="Admin")][HttpPut("{id:int}")]public async Task<IActionResult>Update(int id,Product input){var p=await db.Products.FindAsync(id);if(p is null)return NotFound(new{message="Product not found."});p.Title=input.Title;p.Description=input.Description;p.Price=input.Price;p.Category=input.Category;p.Thumbnail=input.Thumbnail;p.Stock=input.Stock;p.Rating=input.Rating;p.IsFeatured=input.IsFeatured;await db.SaveChangesAsync();return Ok(p);}
[Authorize(Roles="Admin")][HttpDelete("{id:int}")]public async Task<IActionResult>Delete(int id){var p=await db.Products.FindAsync(id);if(p is null)return NotFound();db.Products.Remove(p);await db.SaveChangesAsync();return NoContent();}}
